### ISSUE TITLE
include cheesepi as cp, modules will not load

### ISSUE THREAD

**Issue by stephenmac98** [liamjjmcnamara/cheesepi#5]
I want to use cheesepi on my pi to monitory my home network, but I cannot get it to run. I have tried installing from pip3 and pulling from the github repo. Both seem to have the same error

Traceback (most recent call last):
  File "/usr/local/bin/cheesepi", line 6, in <module>
    from cheesepi.utils import console_script
  File "/usr/local/lib/python3.7/dist-packages/cheesepi/__init__.py", line 29, in <module>
    import config
ModuleNotFoundError: No module named 'config'

When you had it running with python3 syntax, how were you running it, how can I get it to run?

This was on a fresh install of raspbian.

This error seems to be coming from the line include cheesepi as cp, because removing that line in the files allows more of the code to run. I have tried stripping it down to just utils and config, but even still I cannot get it to work, and the line include cheesepi as cp is the source of the error unless its removed. Then there are new errors

**Comment by thewriteway** [comment]
had same issue on recent install, did you resolve it ever? @stephenmac98
